spring:
  datasource:
    url: jdbc:mysql://database-2.c0ps62txf0my.eu-west-1.rds.amazonaws.com:3306/ElevatorTest
    username: root
    password: testPASS111!
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true